In [23]:
from myGenerator import TestGenerator
import pandas as pd
import json
import numpy as np

In [24]:
def spectraLoader(inputPath: str) -> pd.DataFrame:
    df = pd.DataFrame()
    with open(inputPath, encoding='utf-8') as f:
        for line in f:
            jsonline = json.loads(line)
            lineDf = pd.DataFrame({'id':jsonline['id'], 'spectra':[np.array(jsonline['spectra'])]})
            df = pd.concat([df, lineDf])
    df = df.reset_index(drop=True)

    return df

In [25]:
test = pd.read_pickle("tmp/PanTest.plk")
full_spectra = spectraLoader('tmp/FullSpectra.jsonl')
list_IDs = test.id.unique().tolist()

In [31]:
test.idtext.unique().shape

(80,)

In [28]:
print(test.shape[0]/2)
print(full_spectra.shape)
print(len(list_IDs))


1070.0
(80, 2)
1070


In [44]:
full_spectra.spectra[0].shape

(3, 20, 20)

In [63]:

params = {'dim': (1200,),
    'batch_size': 3}
x = TestGenerator(list_IDs, test, full_spectra, **params)

In [64]:
x.__getitem__(3)[0]

(array([[26.1542778 , 14.27299404, 13.26203156, ..., 11.74957752,
         11.53381729, 11.30260658],
        [29.17065811, 15.41231823, 14.13848495, ..., 20.87254143,
         20.00380898, 19.13000679],
        [25.55375099, 13.72375488, 12.96818161, ..., 11.59582806,
         11.40086555, 11.18942928]]),
 array([[28.93564606, 15.21465588, 14.23000622, ..., 11.75096893,
         11.54677868, 11.32604408],
        [27.69133377, 14.78660393, 14.00065613, ..., 19.37652397,
         18.64108467, 17.8952446 ],
        [28.93564606, 15.21465588, 14.23000622, ..., 11.75096893,
         11.54677868, 11.32604408]]))

In [69]:
x.__getitem__(78)[0]

(array([[29.64274406, 15.33604622, 14.16795349, ..., 14.16557693,
         13.84510136, 13.50369263],
        [24.34172821, 13.67500973, 12.83590126, ..., 11.31101131,
         11.11130428, 10.89716625],
        [20.91234016, 11.91053677, 11.2152195 , ...,  3.21520019,
          3.20345449,  3.18994045]]),
 array([[34.508358  , 17.2412014 , 15.92423344, ..., 16.77318382,
         16.28476715, 15.7741642 ],
        [24.02702141, 13.76861   , 13.12093544, ...,  9.5076437 ,
          9.37137222,  9.22424412],
        [26.23565865, 14.13490105, 13.2123003 , ..., 17.65644073,
         17.08492279, 16.49482536]]))