In [1]:
from myGenerator import TestGenerator
import pandas as pd
import json
import numpy as np

In [2]:
def spectraLoader(inputPath: str) -> pd.DataFrame:
    df = pd.DataFrame()
    with open(inputPath, encoding='utf-8') as f:
        for line in f:
            jsonline = json.loads(line)
            lineDf = pd.DataFrame({'id':jsonline['id'], 'spectra':[np.array(jsonline['spectra'])]})
            df = pd.concat([df, lineDf])
    df = df.reset_index(drop=True)

    return df

In [3]:
test = pd.read_pickle("tmp/PanTest.plk")
full_spectra = spectraLoader('tmp/FullSpectra.jsonl')
list_IDs = test.id.unique().tolist()

In [4]:
test.idtext.unique().shape

(80,)

In [5]:
print(test.shape[0]/2)
print(full_spectra.shape)
print(len(list_IDs))


1070.0
(80, 2)
1070


In [6]:
full_spectra.spectra[0].shape

(3, 20, 20)

In [32]:

params = {'dim': (1200,),
    'batch_size': 3}
x = TestGenerator(list_IDs, test, full_spectra, **params)
x.__len__()

356

In [16]:
x.__getitem__(3)[0]

(array([[0.15246226, 0.15246724, 0.15247206, ..., 0.10410175, 0.10306609,
         0.10192958],
        [0.19510923, 0.19511451, 0.1951196 , ..., 0.18783833, 0.18359227,
         0.17909551],
        [0.17649008, 0.17648965, 0.17648904, ..., 0.11174673, 0.11029722,
         0.10874657]]),
 array([[0.22696641, 0.22698736, 0.22700804, ..., 0.10326645, 0.10220364,
         0.10104379],
        [0.19849892, 0.19850916, 0.19851921, ..., 0.14364623, 0.14146663,
         0.13910694],
        [0.22696641, 0.22698736, 0.22700804, ..., 0.10326645, 0.10220364,
         0.10104379]]))

In [43]:
x.__getitem__(1000)[0]

(array([[6.94578460e-310, 4.66435100e-310, 0.00000000e+000, ...,
         1.43886372e-001, 1.41774565e-001, 1.39476091e-001],
        [4.75093525e-320, 4.75093525e-320, 3.20624225e-002, ...,
         1.14421822e-001, 1.13191478e-001, 1.11837804e-001],
        [1.10372111e-001, 1.08806022e-001, 0.00000000e+000, ...,
         1.11564070e-001, 1.10952370e-001, 1.10199749e-001]]),
 array([[0.10716889, 0.1059292 , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ]]))

In [10]:
batch = x.__getitem__(50)[0]
batch[0]==batch[1]

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])