In [1]:
from myGenerator import TestGenerator
import pandas as pd
import json
import numpy as np

In [2]:
def spectraLoader(inputPath: str) -> pd.DataFrame:
    df = pd.DataFrame()
    with open(inputPath, encoding='utf-8') as f:
        for line in f:
            jsonline = json.loads(line)
            lineDf = pd.DataFrame({'id':jsonline['id'], 'spectra':[np.array(jsonline['spectra'])]})
            df = pd.concat([df, lineDf])
    df = df.reset_index(drop=True)

    return df

In [3]:
test = pd.read_pickle("tmp/PanTest.plk")
full_spectra = spectraLoader('tmp/FullSpectra.jsonl')
list_IDs = test.id.unique().tolist()

In [4]:
test.idtext.unique().shape

(80,)

In [5]:
print(test.shape[0]/2)
print(full_spectra.shape)
print(len(list_IDs))


1070.0
(80, 2)
1070


In [6]:
full_spectra.spectra[0].shape

(3, 20, 20)

In [7]:

params = {'dim': (400,),
    'batch_size': 3}
x = TestGenerator(list_IDs, test, full_spectra, **params)
x.__len__()

356

In [8]:
x.__getitem__(3)[0]

(array([[0.05227315, 0.05582004, 0.05936424, ..., 0.06338031, 0.05962714,
         0.0558533 ],
        [0.06184945, 0.06640537, 0.07100566, ..., 0.06515949, 0.06094795,
         0.05679216],
        [0.05499554, 0.05874949, 0.06249575, ..., 0.0602979 , 0.05673597,
         0.05316071]]),
 array([[0.05243937, 0.05582409, 0.05916587, ..., 0.05531412, 0.05220148,
         0.04905502],
        [0.06175036, 0.06642928, 0.07118971, ..., 0.06858398, 0.06408539,
         0.05965142],
        [0.05243937, 0.05582409, 0.05916587, ..., 0.05531412, 0.05220148,
         0.04905502]]))

In [12]:
x.__getitem__(4)[0]

(array([[0.06175036, 0.06642928, 0.07118971, ..., 0.06858398, 0.06408539,
         0.05965142],
        [0.05243937, 0.05582409, 0.05916587, ..., 0.05531412, 0.05220148,
         0.04905502],
        [0.05499554, 0.05874949, 0.06249575, ..., 0.0602979 , 0.05673597,
         0.05316071]]),
 array([[0.05116475, 0.0543617 , 0.05749842, ..., 0.05639078, 0.05313303,
         0.04985589],
        [0.01183729, 0.01228332, 0.01267768, ..., 0.01045735, 0.00992327,
         0.00935442],
        [0.06219704, 0.06700671, 0.07192437, ..., 0.06972629, 0.06514866,
         0.06063408]]))

In [33]:
batch = x.__getitem__(50)[0]
batch[0]==batch[1]

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])