In [1]:
import json
import numpy as np

In [31]:
with open('.\outputs\SalidaAssembler.jsonl') as f:
    x = json.loads(f.readline())
np.array(x['spectra'])

array([[[0.10736861, 0.30771362, 0.51741727, 0.54772756],
        [0.62384075, 0.73016849, 0.44596497, 0.67105748],
        [0.3191422 , 0.76415047, 0.02596446, 0.95479546],
        [0.50526848, 0.72720302, 0.38028918, 0.9290391 ]],

       [[0.1231091 , 0.98673904, 0.3002507 , 0.23475335],
        [0.60929655, 0.49848608, 0.80713493, 0.02129509],
        [0.46318896, 0.76994454, 0.06870332, 0.78126018],
        [0.07948894, 0.79726274, 0.10828344, 0.82678721]],

       [[0.29493411, 0.55305999, 0.54120834, 0.97826833],
        [0.50659276, 0.72041865, 0.30128875, 0.41933129],
        [0.54482147, 0.42140926, 0.82312144, 0.22127614],
        [0.42155464, 0.14387562, 0.47869579, 0.5456912 ]]])

In [27]:
with open('../data\data_dummy_spectre_lexic.jsonl') as f:
    lex = json.loads(f.readline())
np.array(lex['spectre'])


array([[0.10736861, 0.30771362, 0.51741727, 0.54772756],
       [0.62384075, 0.73016849, 0.44596497, 0.67105748],
       [0.3191422 , 0.76415047, 0.02596446, 0.95479546],
       [0.50526848, 0.72720302, 0.38028918, 0.9290391 ]])

In [28]:
with open('../data\data_dummy_spectre_syntactic.jsonl') as f:
    lex = json.loads(f.readline())
np.array(lex['spectre'])


array([[0.1231091 , 0.98673904, 0.3002507 , 0.23475335],
       [0.60929655, 0.49848608, 0.80713493, 0.02129509],
       [0.46318896, 0.76994454, 0.06870332, 0.78126018],
       [0.07948894, 0.79726274, 0.10828344, 0.82678721]])

In [29]:
with open('../data\data_dummy_spectre_semantic.jsonl') as f:
    lex = json.loads(f.readline())
np.array(lex['spectre'])


array([[0.29493411, 0.55305999, 0.54120834, 0.97826833],
       [0.50659276, 0.72041865, 0.30128875, 0.41933129],
       [0.54482147, 0.42140926, 0.82312144, 0.22127614],
       [0.42155464, 0.14387562, 0.47869579, 0.5456912 ]])

In [24]:
import sys
sys.path.append('..')
import spectraltrep.layerConsolidation as lc

sr = lc.SpectraReader('../data/data_dummy_spectre_lexic.jsonl')
gen = sr.readSpectra()
next(gen)

(0,
 [[0.09883595404972134, 0.9469017120742927, 0.9453244653180863],
  [0.7423295855870357, 0.7751673187229307, 0.33318939312528495],
  [0.6571134551137403, 0.3150627263927771, 0.24074688246472842]])